### ISSUE TITLE
Basic Documentation

### ISSUE THREAD

**Issue by Moosems** [Akascape/TkNodeSystem#2]
Could a page or two of basic documentation be created for this? I'm very interested in the library but am not sure how it works.

**Comment by Akascape** [comment]
@Moosems 
Here is the documentation: https://github.com/Akascape/TkNodeSystem/wiki

Can you expain what I should add in the docs?

**Comment by Moosems** [comment]
I would have added that to the repo readme :).

**Comment by Akascape** [comment]
@Moosems 
As the library has various components, I have created a separate wiki page. Usually I add the documentation in the readme if the project is small.
